// The error index on sheratan.dev (SPEC §8, §10): one page per code that the
// runtime throws or the checker reports, and a page listing them all. Built
// from the same table `sheratan explain` prints, so the page an error links to
// and the answer the command gives cannot disagree, and every example on it is
// one `test/explain.test.ts` has executed. Pure functions only; `errors.ts`
// owns the file system.

import { DOCS_BASE_URL } from '../../core/src/codes.ts';
import { CaughtBy, type ExampleFiles, type Explanation } from '../src/explain/explanation.ts';

/** Where the index lives on the site, and the prefix every code's page sits under. */
export const ERRORS_PATH = '/errors/';

/** Brackets the part of `site/sitemap.xml` this generator owns. */
export const SITEMAP_START = '<!-- generated by packages/cli/scripts/errors.ts -->';

/** Ends the generated part of the sitemap. */
export const SITEMAP_END = '<!-- end generated -->';

/** The index's canonical address: the base every error URL is built on. */
const INDEX_URL = DOCS_BASE_URL;

const ESCAPES: Readonly<Record<string, string>> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
};

/** Text made safe to place anywhere in HTML, attribute values included. */
export function escapeHtml(text: string): string {
  return text.replaceAll(/[&<>"']/g, (char) => ESCAPES[char] ?? char);
}

/** A sentence from the table, where `backticks` mark code, as HTML. */
export function prose(text: string): string {
  return text
    .split('`')
    .map((part, index) => (index % 2 === 0 ? escapeHtml(part) : `<code>${escapeHtml(part)}</code>`))
    .join('');
}

/** A page's address on the site. A trailing slash, because each page is a directory. */
export function pathFor(code: string): string {
  return `${ERRORS_PATH}${code}/`;
}

// No script on any page, so the policy needs no hash to keep current. Fonts
// come from this origin, as on the landing page.
const POLICY =
  "default-src 'none'; style-src 'unsafe-inline'; font-src 'self'; img-src 'self' data:; " +
  "base-uri 'none'; form-action 'none'";

// The landing page's tokens and type (site/index.html), cut to what these
// pages use. Light only, for the same reason the landing page gives.
const STYLE = `
  @font-face { font-family: Archivo; font-style: normal; font-weight: 300 500; font-display: swap; src: url(/fonts/archivo-latin.woff2) format('woff2'); }
  @font-face { font-family: "IBM Plex Mono"; font-style: normal; font-weight: 400; font-display: swap; src: url(/fonts/ibm-plex-mono-latin.woff2) format('woff2'); }
  :root {
    --ground: #FAFAF8; --ink: #000000; --t66: rgba(0, 0, 0, 0.66); --t55: rgba(0, 0, 0, 0.55);
    --hair: rgba(0, 0, 0, 0.12); --curve: 0.12;
    --sans: Archivo, "Helvetica Neue", Helvetica, Arial, sans-serif;
    --mono: "IBM Plex Mono", ui-monospace, "SF Mono", Menlo, Consolas, monospace;
  }
  * { box-sizing: border-box; }
  html { color-scheme: light; }
  body { margin: 0; background: var(--ground); color: var(--ink); font: 300 16px/1.7 var(--sans); padding-inline: max(16px, 5vw); -webkit-font-smoothing: antialiased; }
  a { color: inherit; }
  :focus-visible { outline: 1px solid var(--ink); outline-offset: 4px; }
  code, pre { font-family: var(--mono); }
  p code, h1 code, li code, td code { font-size: 0.9em; }
  .wrap { max-width: 880px; margin: 0 auto; }
  .nav { display: flex; align-items: center; justify-content: space-between; gap: 24px; padding-block: 28px; flex-wrap: wrap; border-bottom: 1px solid var(--hair); }
  .lockup { display: flex; align-items: center; gap: 18px; text-decoration: none; }
  .lockup .rule { width: 1px; height: 22px; background: var(--hair); }
  .wordmark { font-size: 15px; font-weight: 400; letter-spacing: 0.36em; text-indent: 0.36em; text-transform: lowercase; line-height: 1; }
  .mark .curve { stroke-opacity: var(--curve); }
  .navlink { font-size: 11px; font-weight: 400; letter-spacing: 0.24em; text-transform: uppercase; text-decoration: none; }
  .navlink:hover { color: var(--t55); }
  main { display: flex; flex-direction: column; gap: 56px; padding-block: 64px 96px; }
  .label { margin: 0; font-size: 10px; font-weight: 400; line-height: 1.4; letter-spacing: 0.34em; text-transform: uppercase; color: var(--t55); }
  header { display: flex; flex-direction: column; gap: 20px; }
  h1 { margin: 0; font-size: clamp(32px, 5vw, 52px); font-weight: 300; line-height: 1.1; letter-spacing: -0.02em; text-wrap: balance; }
  h1 .code { display: block; font: 400 0.42em var(--mono); letter-spacing: 0.04em; color: var(--t55); margin-bottom: 14px; }
  h2 { margin: 0; font-size: 22px; font-weight: 400; }
  .lead { margin: 0; max-width: 62ch; font-size: 17px; color: var(--t66); text-wrap: pretty; }
  section { display: flex; flex-direction: column; gap: 16px; }
  .caption { margin: 0; font-size: 13px; color: var(--t55); }
  figure { margin: 0; border: 1px solid var(--hair); }
  figcaption { font: 400 12px var(--mono); color: var(--t55); padding: 10px 16px; border-bottom: 1px solid var(--hair); overflow-wrap: anywhere; }
  pre { margin: 0; padding: 16px; font-size: 13px; line-height: 1.7; overflow-x: auto; }
  .files { display: flex; flex-direction: column; gap: 12px; }
  .ask { margin: 0; padding: 16px; border: 1px solid var(--hair); font-size: 13px; overflow-x: auto; }
  table { width: 100%; border-collapse: collapse; font-size: 14px; }
  th, td { text-align: left; padding: 12px 8px 12px 0; border-bottom: 1px solid var(--hair); vertical-align: baseline; }
  th { font-size: 10px; font-weight: 400; letter-spacing: 0.2em; text-transform: uppercase; color: var(--t55); }
  td.code a { font: 400 13px var(--mono); white-space: nowrap; }
  td.muted { color: var(--t55); white-space: nowrap; }
  @media (max-width: 600px) { .hide-narrow { display: none; } }
  footer { border-top: 1px solid var(--hair); padding-block: 28px 48px; font-size: 12px; color: var(--t55); }
`;

// The mark from Docs/sheratan-identity.html. Coordinates fixed by the identity.
const MARK = `<svg class="mark" width="34" height="34" viewBox="0 0 64 64" aria-hidden="true">
      <path class="curve" d="M8 48 Q33 38 56 16" fill="none" stroke="currentColor" stroke-width="1" vector-effect="non-scaling-stroke"/>
      <circle cx="8" cy="48" r="1.4" fill="currentColor"/>
      <circle cx="30.5" cy="37.2" r="3.2" fill="currentColor"/>
      <circle cx="56" cy="16" r="2" fill="currentColor"/>
    </svg>`;

/** What a page says about itself to the browser, search and link previews. */
interface Head {
  readonly title: string;
  readonly description: string;
  readonly canonical: string;
}

/** The document every page shares: policy, style, the lockup and the footer. */
function shell(head: Head, body: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Generated by packages/cli/scripts/errors.ts from sheratan explain's table. Do not edit. -->
<meta http-equiv="Content-Security-Policy" content="${POLICY}">
<meta name="referrer" content="strict-origin-when-cross-origin">
<meta name="theme-color" content="#FAFAF8">
<title>${escapeHtml(head.title)}</title>
<meta name="description" content="${escapeHtml(head.description)}">
<link rel="canonical" href="${head.canonical}">
<style>${STYLE}</style>
</head>
<body>
<div class="wrap">
  <nav class="nav" aria-label="Primary">
    <a class="lockup" href="/" aria-label="sheratan home">
    ${MARK}
      <span class="rule"></span>
      <span class="wordmark">sheratan</span>
    </a>
    <a class="navlink" href="${ERRORS_PATH}">All errors</a>
  </nav>
  <main>
${body}
  </main>
  <footer>Every example here is run by Sheratan's test suite: the wrong one must be caught with its code, the right one must not.</footer>
</div>
</body>
</html>
`;
}

/** Each file as its path over its source. */
function filesHtml(example: ExampleFiles): string {
  const figures = Object.entries(example).map(
    ([path, source]) =>
      `      <figure><figcaption>${escapeHtml(path)}</figcaption><pre><code>${escapeHtml(source.trimEnd())}</code></pre></figure>`,
  );

  return `    <div class="files">\n${figures.join('\n')}\n    </div>`;
}

/** Where a code is caught and how loudly, in the words the page uses. */
function kindOf(entry: Explanation): string {
  const where =
    entry.caughtBy === CaughtBy.Checker ? 'caught by sheratan check' : 'thrown at run time';

  return `${entry.severity} · ${where}`;
}

/** What happens to the wrong example, and to the right one. */
function outcomes(entry: Explanation): { readonly wrong: string; readonly right: string } {
  if (entry.caughtBy === CaughtBy.Checker) {
    return { wrong: `<code>sheratan check</code> reports ${entry.code}.`, right: 'Checks clean.' };
  }

  return { wrong: `Throws ${entry.code}.`, right: 'Runs without it.' };
}

/** One code's page: what it is, why, code that is caught beside code that is not. */
export function pageFor(entry: Explanation): string {
  const outcome = outcomes(entry);

  const body = `    <header>
      <p class="label">${escapeHtml(kindOf(entry))}</p>
      <h1><span class="code">${entry.code}</span>${prose(entry.title)}</h1>
      <p class="lead">${prose(entry.why)}</p>
    </header>
    <section aria-labelledby="wrong">
      <h2 id="wrong">Wrong</h2>
      <p class="caption">${outcome.wrong}</p>
${filesHtml(entry.wrong)}
    </section>
    <section aria-labelledby="right">
      <h2 id="right">Right</h2>
      <p class="caption">${outcome.right}</p>
${filesHtml(entry.right)}
    </section>
    <section aria-labelledby="terminal">
      <h2 id="terminal">In your terminal</h2>
      <pre class="ask"><code>sheratan explain ${entry.code}          # this page
sheratan explain ${entry.code} --json   # the same, for an agent</code></pre>
    </section>`;

  return shell(
    {
      title: `${entry.code}: ${entry.title.replaceAll('`', '')} · Sheratan`,
      description: entry.why,
      canonical: `${INDEX_URL}${entry.code}/`,
    },
    body,
  );
}

/** One row of the index table. */
function row(entry: Explanation): string {
  return `        <tr><td class="code"><a href="${pathFor(entry.code)}">${entry.code}</a></td><td>${prose(entry.title)}</td><td class="muted hide-narrow">${escapeHtml(kindOf(entry))}</td></tr>`;
}

/** Every code on one page, for a reader who has a symptom and not a code. */
export function indexPage(all: readonly Explanation[], reserved: readonly string[]): string {
  const body = `    <header>
      <p class="label">Error index</p>
      <h1>Every error Sheratan reports, and how to fix it</h1>
      <p class="lead">Each page shows code that triggers the error beside code that doesn't. The examples are run by the test suite, so none of them can go out of date.</p>
    </header>
    <section aria-labelledby="codes">
      <h2 id="codes">${all.length} codes</h2>
      <table>
        <thead><tr><th scope="col">Code</th><th scope="col">What it means</th><th scope="col" class="hide-narrow">Kind</th></tr></thead>
        <tbody>
${all.map(row).join('\n')}
        </tbody>
      </table>
    </section>
    <section aria-labelledby="reserved">
      <h2 id="reserved">Numbered, not checked yet</h2>
      <p class="caption">${reserved.map((code) => `<code>${escapeHtml(code)}</code>`).join(', ')}: reserved by the spec, and given a page in the release that starts checking them.</p>
    </section>`;

  return shell(
    {
      title: 'Error index · Sheratan',
      description:
        'Every error the Sheratan runtime throws and its checker reports, each with code that triggers it beside code that does not.',
      canonical: INDEX_URL,
    },
    body,
  );
}

/** The sitemap entries this generator owns: the index, then each code. */
export function sitemapSection(all: readonly Explanation[]): string {
  const urls = [INDEX_URL, ...all.map((entry) => `${INDEX_URL}${entry.code}/`)];

  return urls.map((url) => `  <url>\n    <loc>${url}</loc>\n  </url>`).join('\n');
}

/** `sitemap` with its generated part replaced by `section`. Throws if the markers are missing. */
export function withSitemapSection(sitemap: string, section: string): string {
  const start = sitemap.indexOf(SITEMAP_START);
  const end = sitemap.indexOf(SITEMAP_END);

  if (start === -1 || end < start) {
    throw new Error(
      `site/sitemap.xml needs the lines ${SITEMAP_START} and ${SITEMAP_END} around the generated entries.`,
    );
  }

  return `${sitemap.slice(0, start + SITEMAP_START.length)}\n${section}\n  ${sitemap.slice(end)}`;
}

/** Why the files on disk differ from what would be generated: missing, stale or orphaned, by path. */
export function staleness(
  expected: ReadonlyMap<string, string>,
  actual: ReadonlyMap<string, string>,
): readonly string[] {
  const problems: string[] = [];

  for (const [path, content] of expected) {
    const found = actual.get(path);

    if (found === undefined) problems.push(`${path} is missing`);
    else if (found !== content) problems.push(`${path} is stale`);
  }

  for (const path of actual.keys()) {
    if (!expected.has(path)) problems.push(`${path} is not generated from any code; remove it`);
  }

  return problems.toSorted();
}
